# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=20)),
                ('costperfood', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=20)),
                ('reviews', models.CharField(max_length=300)),
                ('menu', models.CharField(max_length=300)),
                ('deals', models.CharField(max_length=300)),
            ],
        ),
    ]
