# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20170501_1928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='deals',
        ),
    ]
